apiVersion: v1
kind: Service
metadata:
  name: fastapi-backend
  namespace: devops-dev
spec:
  selector:
    app: fastapi-backend
  ports:
    - port: 80  # Puerto del servicio
      targetPort: 8000  # Puerto del contenedor
      nodePort: 32001  # Puerto en el nodo
  type: NodePort  # Permite acceder al servicio desde fuera del clúster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-backend
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-backend
  template:
    metadata:
      labels:
        app: fastapi-backend
    spec:
      containers:
        - name: fastapi-backend  # Nombre del contenedor
          image: cristianbenavides/fastapi-backend  # Imagen de tu aplicación FastAPI
          env:
            - name: DATABASE_URL
              value: "mysql://root:@mysql-service:3306/dbusers"
          ports:
            - containerPort: 8000  # Puerto expuesto del contenedor
      restartPolicy: Always  # Reinicia si falla
