apiVersion: v1
kind: Service
metadata:
  name: mysql-pv-claim
  namespace: devops-dev
spec:
  selector:
    app: postgres
  ports:
    
port: 5432
    targetPort: 5432
clusterIP: None  # Solo accesible dentro del clúster
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        
name: postgres
        image: postgres:latest
        env:
name: POSTGRES_DB
          value: "mydb"
name: POSTGRES_USER
        value: "postgres"
name: POSTGRES_PASSWORD
      value: "password"
  ports:
containerPort: 5432